"""
MiniPar CLI — command-line interface for the MiniPar compiler.

Usage:
    python src/minipar_cli.py compile <file> [options]
    python src/minipar_cli.py ast <file>
    python src/minipar_cli.py tac <file>
    python src/minipar_cli.py generate-c <file> [--out output.c]
    python src/minipar_cli.py generate-arm <file>
    python src/minipar_cli.py test
"""

import argparse
import os
import subprocess
import sys

# Ensure project root is on the path so `src.*` imports resolve correctly.
_ROOT = os.path.join(os.path.dirname(__file__), "..")
sys.path.insert(0, os.path.abspath(_ROOT))

from src.compiler import compile_file  # noqa: E402


# ---------------------------------------------------------------------------
# Subcommand handlers
# ---------------------------------------------------------------------------

def _cmd_compile(args):
    compile_file(
        args.file,
        show_tokens=args.tokens,
        show_ast=args.ast,
        show_semantic=args.semantic,
        generate_c=args.generate_c,
        c_output=args.out,
        compile_exe=args.exe,
        generate_asm=not args.no_asm,
    )


def _cmd_ast(args):
    compile_file(args.file, show_ast=True, generate_asm=False)


def _cmd_tac(args):
    compile_file(args.file, generate_asm=False)


def _cmd_generate_c(args):
    compile_file(args.file, generate_c=True, c_output=args.out, generate_asm=False)


def _cmd_generate_arm(args):
    compile_file(args.file, generate_asm=True)


def _cmd_test(args):
    root = os.path.abspath(_ROOT)
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "tests/", "-q"],
        cwd=root,
    )
    sys.exit(result.returncode)


# ---------------------------------------------------------------------------
# Argument parser
# ---------------------------------------------------------------------------

def _build_parser():
    p = argparse.ArgumentParser(
        prog="minipar",
        description="MiniPar compiler — compile, inspect, and test MiniPar programs.",
    )
    sub = p.add_subparsers(dest="cmd", metavar="<command>")
    sub.required = True

    # compile
    c = sub.add_parser("compile", help="Compile a .minipar file (TAC + optional targets)")
    c.add_argument("file", help="Path to .minipar source file")
    c.add_argument("--tokens", action="store_true", help="Print token stream")
    c.add_argument("--ast", action="store_true", help="Print abstract syntax tree")
    c.add_argument("--semantic", action="store_true", help="Print semantic analysis details")
    c.add_argument("--generate-c", dest="generate_c", action="store_true", help="Generate C code")
    c.add_argument("--generate-arm", dest="generate_arm", action="store_true",
                   help="Generate ARM assembly (same as default; kept for symmetry)")
    c.add_argument("--exe", action="store_true", help="Compile to native executable via GCC")
    c.add_argument("--no-asm", dest="no_asm", action="store_true",
                   help="Skip ARM assembly generation (ARM is generated by default)")
    c.add_argument("--out", metavar="FILE", default=None, help="C output filename (default: output.c)")
    c.set_defaults(func=_cmd_compile)

    # ast
    a = sub.add_parser("ast", help="Print the AST for a .minipar file")
    a.add_argument("file", help="Path to .minipar source file")
    a.set_defaults(func=_cmd_ast)

    # tac
    t = sub.add_parser("tac", help="Print the Three-Address Code for a .minipar file")
    t.add_argument("file", help="Path to .minipar source file")
    t.set_defaults(func=_cmd_tac)

    # generate-c
    gc = sub.add_parser("generate-c", help="Generate C code from a .minipar file")
    gc.add_argument("file", help="Path to .minipar source file")
    gc.add_argument("--out", metavar="FILE", default="output.c", help="Output .c file")
    gc.set_defaults(func=_cmd_generate_c)

    # generate-arm
    ga = sub.add_parser("generate-arm", help="Generate ARM assembly from a .minipar file")
    ga.add_argument("file", help="Path to .minipar source file")
    ga.set_defaults(func=_cmd_generate_arm)

    # test
    te = sub.add_parser("test", help="Run the full MiniPar test suite (pytest)")
    te.set_defaults(func=_cmd_test)

    return p


def main():
    parser = _build_parser()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
